---
name: networkautomaniac-telemetry

services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    user: telegraf:${DOCKER_GROUP_ID}
    command: telegraf --config /etc/telegraf/telegraf.conf --watch-config poll
    volumes:
      - ./configs/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:v0.45.0
  #   container_name: cadvisor
  #   hostname: cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   ports:
  #     - 9100:8080
  #   restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - telegraf
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}
    volumes:
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./configs/grafana/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
