---
apiVersion: 1
deleteDatasources:
  - name: "Prometheus"
    orgId: 1
  - name: "Loki"
    orgId: 1
datasources:
  - name: "Prometheus"
    type: "prometheus"
    orgId: 1
    url: "${PROMETHEUS_URL}"
    editable: true
  - name: "Loki"
    type: "loki"
    orgId: 1
    url: "${LOKI_URL}"
    editable: true
